-  hosts: 
    - googlemaster
    - googleknoten
   remote_user: bruno
   connection: ssh
   gather_facts: true
   become: yes
   tasks:
     - name: Gather facts
       ansible.builtin.debug:
          var: ansible_facts

